### ISSUE TITLE
Rename plugin from 'OMQuickHelp' to 'OMDashHelp' on Alcatraz

### ISSUE THREAD

**Issue by rsanchezsaez** [omz/Dash-Plugin-for-Xcode#31]
It's impossible to remember and/or find it on Alcatraz without having to Google for it.

**Comment by Kapeli** [comment]
The latest Alcatraz shows "OMQuickHelp" even when you search for "Dash". This issue is not really a huge problem any more so I'll close it.

**Comment by Phenmod** [comment]
@Kapeli Please add install via Alcatraz  "OMQuickHelp" in "README.md"

**Comment by Kapeli** [comment]
Added.
