### ISSUE TITLE
Bind docsets to Xcode instead of substitute help panel

### ISSUE THREAD

**Issue by Skippern** [omz/Dash-Plugin-for-Xcode#34]
It would be nice if the docsets could be bound to Xcode, and open them in the default reader window instead of substituting the reader window with `Dash`. I have another app, `Docs for Xcode` that binds the documents directly into Xcode (I haven't figured out how it does it yet), and docsets installed by `Docs for Xcode` continues to show, even after Xcode have been updated.

A simple copy of the docsets to the location `Docs for Xcode` uses did not install them, so there must be some `.plist` or some other resource taking care of this

**Comment by Kapeli** [comment]
This is the Dash Xcode plugin and its goal is to replace Xcode's documentation viewer with Dash, not to provide Xcode with docsets.
