### ISSUE TITLE
Xcode 6.4 beta 2 (6E14) doesn't like the plug-in 

### ISSUE THREAD

**Issue by HiddenJester** [omz/Dash-Plugin-for-Xcode#37]
(I suspect you may already be aware, but just in case…)

I was trying to use the 6.4 beta because of the note posted at the top of [Apple's Swift forum](https://devforums.apple.com/community/tools/languages/swift), to wit:

>Xcode 6.3.1 introduced a compile-time regression for Swift apps which is likely to impact the compile time of larger projects using Swift frameworks or using projects supplied from external sources (e.g. CocoaPods).
Xcode 6.4 beta fixes this problem so should be used as a workaround if this problem is affecting your current development.
Until Xcode 6.4 is released, App Store submissions still need to be built with Xcode 6.3.1.

Of course, the Dash-plugin stopped working. I tried adding the output of `defaults read /Applications/Xcode-beta.app/Contents/Info DVTPlugInCompatibilityUUID` to DVTPlugInCompatabilityUUIDs in the Info.plist which got me to an "Unexpected Code Bundles" dialog (see [this image](https://devforums.apple.com/thread/268630?tstart=0) for an example.) Clicking "Load Bundles" made the dialog go away, and I had the menu items for Dash in the Help menu, but neither "Replace Quick Help" or "Replace Quick Help Reference Link" seemed to bring up Dash.

Turns out I'm not personally seeing the Swift issue mentioned above so I just reverted to 6.3.1 for now, but obviously 6.4 is all of our future's :-)

**Comment by Kapeli** [comment]
I was not aware of this. Thanks. I'll look into it.

**Comment by Kapeli** [comment]
Took a brief look... As far as I can tell Xcode 6.4 changes how plugins (and possibly Xcode frameworks) are loaded. 

The plugin is loaded before the other frameworks are loaded, so when the plugin tries to swizzle `IDESourceCodeEditor`, the class doesn't exist yet. I need to figure out a way to get notified when the class loads and swizzle after that.

**Comment by Kapeli** [comment]
https://github.com/omz/Dash-Plugin-for-Xcode/commit/3014f12c4e91a6be3a0521600f65879acae05b0a should fix this. Thanks for letting me know!
