### ISSUE TITLE
Xcode 6.3.2 Dash plugin not working.

### ISSUE THREAD

**Issue by jkyin** [omz/Dash-Plugin-for-Xcode#39]
I can not find Dash plugin in help menu, and also not working for searching document.

**Comment by notzeist** [comment]
I'm having the same issue, plugin loads fine but doesn't seem to actually work or show up in any menu.

**Comment by liuxuan30** [comment]
have you updated your dash plugin source code and rebuild again? I did this, and Dash works as usual.

**Comment by jkyin** [comment]
@notzeist @liuxuan30 I has deleted and rebuild again. But it still doesn't work.

**Comment by jkyin** [comment]
I select "load bundles" and then it works.

**Comment by liuxuan30** [comment]
what you mean "load bundles" ?

**Comment by Kapeli** [comment]
> what you mean "load bundles" ?

The latest Xcode version (6.3.2) asks you at launch if you want to load plugin bundles.

**Comment by liuxuan30** [comment]
alright, I don't remember I had that pop up. Glad it works for you

**Comment by edwardIshaq** [comment]
I had to delete the plugin, re checkout the code and install it again for Xcode to pop up that "Load Bundle" alert on application load.
What seemed weird to me is that when I deleted and ran the code the plugin alert didn't show even though the bundle was installed in the /Library/Application Support/... folder...

Thank you Xiaoyu Yin & Bogdan Popescu
