### ISSUE TITLE
Dash menu not showing up in Xcode Version 6.3.2 (6D2105)

### ISSUE THREAD

**Issue by edwardIshaq** [omz/Dash-Plugin-for-Xcode#40]
I had the plugin work earlier, but it seems its not getting picked up after the latest release of Xcode.
I tried running the project again but no luck.

Any suggestions on how to get it back ? 

Thanks,
Eddie

**Comment by Kapeli** [comment]
Try grabbing a fresh clone of the project and rebuilding. If it still doesn't work, check Console.app for any messages regarding OMQuickHelp.

**Comment by jkyin** [comment]
@edwardIshaq Your Xcode is 6.3.2 ? Look this https://github.com/omz/Dash-Plugin-for-Xcode/issues/39

**Comment by edwardIshaq** [comment]
I do have that 6.3.2 version. I"ll close this and comment on #39
