### ISSUE TITLE
Xcode 7.0 GM

### ISSUE THREAD

**Issue by AndrewAKing** [omz/Dash-Plugin-for-Xcode#44]
The plugin has been working for me throughout the various Xcode betas but now isn't working in the GM seed. I tried deleting it from '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins' and then reinstalling, but upon restarting Xcode after building the project I get no prompt to allow the plugin. I've checked to make sure it's being copied to the Plugin-ins folder during the build, which it is.

It is working with the Xcode 7.1 beta however when I option click methods / properties they seem to default search to Google. For example if you option click on `NSObject` Dash Google searches `c:objc(cs)NSObject`.

**Comment by Kapeli** [comment]
Should be fixed in https://github.com/omz/Dash-Plugin-for-Xcode/commit/e9b0a35eebf0e7ec3b978b1d19eba458c867d18a. Try to reinstall.

> It is working with the Xcode 7.1 beta however when I option click methods / properties they seem to default search to Google. For example if you option click on NSObject Dash Google searches c:objc(cs)NSObject.

This is a separate issue. I'll look into it.
