### ISSUE TITLE
Could not replace the standard Documentation in Xcode7?

### ISSUE THREAD

**Issue by BaiTianyu** [omz/Dash-Plugin-for-Xcode#46]
Hi,

I installed Xcode7  and this plugin from Alcatraz today, but when I open my project, I found Dash can not replace the standard Documentation even I have configured in Help->Dash integration.

Thanks for answer.

**Comment by Kapeli** [comment]
What are you doing exactly and what happens?

**Comment by michaelochs** [comment]
I am experiencing the same issue if:

1. Disable Quick Help Integration is checked
2. Replace Search Documentation is checked

Expected Result:
When I alt-click a method, the quick help opens. When I then click the link to the documentation in the quick help, Dash should open. (This has been the case before Xcode 7).

Actual Result:
When I alt-click a method, the quick help opens. When I then click the link to the documentation in the quick help, the standard Xcode help opens.

**Comment by VinceBurn** [comment]
I have the exact same problem with Xcode : Version 7.0.1 (7A1001)

**Comment by Kapeli** [comment]
"Replace Search Documentation" integration was removed due to changes in Xcode. Please reinstall the plugin.
