### ISSUE TITLE
option-click + double click behaviour changed for Xcode 7.1?

### ISSUE THREAD

**Issue by liuxuan30** [omz/Dash-Plugin-for-Xcode#49]
Hi there,

I am keep using this plugin since Xcode 6. I used to optional-click to get the system popup window for description, and optional- double click to get dash.

Now today I updated Xcode 7.1 and rebuild the plugin, the trick is not working. the option- double click will always call up the xcode document, not dash ( I have enabled the replacement)

What's changed and how do I get my old habbit back? Thanks. It works perfect on 7.0, not sure why 7.1 broke my habbit :(

I don't use any other plugins except dash and vvdocumenter (a comment tool), and I always do a rebuild once the Xcode updated.

**Comment by liuxuan30** [comment]
Well I found some strange behaviour:

let's say for func
```Objective-C
        [UIView transitionWithView:self.window duration:0.3
                           options:UIViewAnimationOptionTransitionFlipFromLeft
                        animations:^{
                            weakSelf.window.rootViewController = rootViewController;
                        }
                        completion:nil];
```
If I option-double click on the function name, it will give me the default documentation;
However if I option-double click on `UIViewAnimationOptionTransitionFlipFromLeft`, it gives me the dash documentation. Seems like a bug.

**Comment by Kapeli** [comment]
The plugin no longer supports this due to changes in Xcode. Use Option-Click to activate Dash.

**Comment by liuxuan30** [comment]
what change causes this? It kinds of degenerates option-click for hud, option-double click for Dash is perfect

**Comment by DanSkeel** [comment]
@Kapeli @liuxuan30 Yeah, that would be awesome if the option-click showed the `quick help popup` and option-double click showed Dash.

Many open source libraries and frameworks provide java doc documentation that is nicely displayed in `quick help popup`. So completely removing popup isn't the best solution I think.

**Comment by Kapeli** [comment]
See https://github.com/omz/Dash-Plugin-for-Xcode/issues/50#issuecomment-153562374.

**Comment by DanSkeel** [comment]
Oh, got you, thanks for effort.
