### ISSUE TITLE
"Replace Search Documentation" doesn't work in Xcode 7

### ISSUE THREAD

**Issue by DZozulya** [omz/Dash-Plugin-for-Xcode#50]
After installing plugin I found that setting "Replace Quick Help" works fine, but I prefer having native quick help, and dash to replace searching in documentation. This setting doesn't work anymore (while "Replace Search Documentation" active, standard documentation is opening instead of Dash).

OS X 10.11.1
Dash 2.2.6
Xcode 7.1

**Comment by Kapeli** [comment]
How do you trigger "Replace Search Documentation" and what happens?

**Comment by liuxuan30** [comment]
I guess it's option+double click... We are all using it from old Xcode but recently it broke

**Comment by Kapeli** [comment]
Option+Double Click is not related to "Search Documentation" and never was.

**Comment by liuxuan30** [comment]
@Kapeli then why I can use option +double click to call Dash up back in time?

**Comment by liuxuan30** [comment]
For now I have to use a hotkey for seach documentation and use it to show dash. It is working.

**Comment by Kapeli** [comment]
Using a hotkey is what the "search documentation" integration is about. As I said, it's not related to Option+Double Click. Please comment on the Option+Double Click integration in its own issue and not here.

**Comment by edo42** [comment]
I'm also experiencing the bug. With both "Replace Quick Help" and "Replace Search Documentation" active, any links clicked in the quick help inspector on the right side now open the default documentation browser.

**Comment by DZozulya** [comment]
> Option+Double Click is not related to "Search Documentation" and never was.

That's weird because I used this to search in dash for year or more, and was really surprised it stop working after some Xcode version released.

**Comment by Kapeli** [comment]
Option+Double Click used to be part of the "Replace Quick Help Reference Link" integration which was removed due to changes in Xcode 7.

**Comment by liuxuan30** [comment]
@Kapeli can't we get over it forever? What changed then? Damn Apple

**Comment by Kapeli** [comment]
They changed the way their links are built within Quick Help and there's no way to reliably get the search string with the new URLs. I think I'll be able to get it to work with Option+Double Click in the same way Option+Click works now, but I'm not sure. It's on my todo list.

**Comment by liuxuan30** [comment]
Cheers! good luck!

**Comment by Kapeli** [comment]
I've looked into it and I couldn't find a way to capture Option+Double Click without side effects. The only way I could get it to work was by returning `nil` in `om_queryResultForToken:ancestorHierarchy:`. Unfortunately, doing this completely breaks the Quick Help sidebar.

**Comment by liuxuan30** [comment]
well then I will get used to the hot keys
