### ISSUE TITLE
Only load if current application is Xcode

### ISSUE THREAD

**Issue by puttin** [omz/Dash-Plugin-for-Xcode#51]
open opendiff(FileMerge) should not load Dash-Plugin

* [Xcode-Plugin-Template/NSObject_Extension.m](https://github.com/kattrali/Xcode-Plugin-Template/blob/9e3563dd988eaf5c63d97b362c0ecc40a749055d/Project%20Templates/Application%20Plug-in/Xcode%20Plugin.xctemplate/NSObject_Extension.m#L15)
* https://github.com/alcatraz/Alcatraz/issues/50
* [Alcatraz/Alcatraz.m](https://github.com/alcatraz/Alcatraz/blob/86b3f9bc4f6c02f929886583c0bebfd5a3053aa5/Alcatraz/Alcatraz.m#L33)

**Comment by Kapeli** [comment]
Fixed. Thank you! :+1:
