### ISSUE TITLE
Plugin installed through Alcatraz is not working

### ISSUE THREAD

**Issue by nrbrook** [omz/Dash-Plugin-for-Xcode#52]
I've removed and added the plugin using Alcatraz. I can see the Dash Integration menu in help. When I option double click a method or click a link in the help pane, it still opens the built in help. Xcode 7.3.1 7D1014

**Comment by Kapeli** [comment]
Option+Double Click and clicking links in the help pane are not supported.

Please see https://github.com/omz/Dash-Plugin-for-Xcode#usage--installation for instructions on how to use the plugin.
