### ISSUE TITLE
option+click does not work in my mac

### ISSUE THREAD

**Issue by WorthyZhang** [omz/Dash-Plugin-for-Xcode#53]
option+click worked good in my device, but recently it doesn't work.
I added NSLog() in source code, and found error info in Console.app like below:
16/5/11 下午1:24:38.008 Xcode[20794]: OMQuickHelp: Couldn't swizzle _searchDocumentationForSelectedText:
16/5/11 下午1:24:38.008 Xcode[20794]: error: Error Domain=NSCocoaErrorDomain Code=-1 "+[NSObject(JRSwizzle) jr_swizzleMethod:withMethod:error:]: original method _searchDocumentationForSelectedText: not found for class IDESourceCodeEditor" UserInfo={NSLocalizedDescription=+[NSObject(JRSwizzle) jr_swizzleMethod:withMethod:error:]: original method _searchDocumentationForSelectedText: not found for class IDESourceCodeEditor}, info: {
    NSLocalizedDescription = "+[NSObject(JRSwizzle) jr_swizzleMethod:withMethod:error:]: original method _searchDocumentationForSelectedText: not found for class IDESourceCodeEditor";

It seems method  _searchDocumentationForSelectedText: does not exists. my Xcode version is 7.3.1, how can i solve this problem?

**Comment by Kapeli** [comment]
Have you tried reinstalling the plugin?

**Comment by WorthyZhang** [comment]
Yes, i have tried reinstalling Xcode,dash and the plugin, the problem still exists.
