### ISSUE TITLE
Alternatives to Xcode extension

### ISSUE THREAD

**Issue by dpcrook** [omz/Dash-Plugin-for-Xcode#56]
I saw blog post on extension for Xcode 8 (https://blog.kapeli.com/dash-xcode-8-and-macos-sierra), and was wondering if there were any kludges/workaround to get a similar behavior from Dash working until the Xcode 8 extension is available?

**Comment by Kapeli** [comment]
The only thing I can think of is the "Search using selected text" option from Preferences > General. I'll leave this issue open in case anyone else has any other ideas.

**Comment by liuxuan30** [comment]
@Kapeli I setup Search using selected text, however nothing happens in Xcode. If I enable 'global search', it will open Dash but not search selected text. Anything I missed?

**Comment by NitroG42** [comment]
Some lead : https://github.com/fpg1503/MakeXcodeGr8Again

**Comment by grandima** [comment]
Can you write a guide, how to use https://github.com/fpg1503/MakeXcodeGr8Again and install Dash plugin?

**Comment by dpcrook** [comment]
There are a few extensions that support searching Dash (via URL mechanism) https://github.com/tib/awesome-xcode-extensions -- though they typical have added it within other features.  I am going to close this issue.
