### ISSUE TITLE
Xcode 9 Beta 5 release note mentions Editor Extension bug fixes

### ISSUE THREAD

**Issue by iOSDeveloperL** [omz/Dash-Plugin-for-Xcode#57]
> Xcode Source Editor Extensions will once again receive multiple selection information from the
source editor, and can once again specify multiple selections in their response. (30746247)

Does that mean this plugin can be installed on Xcode 9 beta 5 ?

[Link](https://download.developer.apple.com/Developer_Tools/Xcode_9_beta_5/Release_Notes_for_Xcode_9_beta_5.pdf)

**Comment by Kapeli** [comment]
No. See https://github.com/omz/Dash-Plugin-for-Xcode#xcode-8-notice.
